[project]
name = "scrambledseg"
version = "0.1.0"
channels = ["conda-forge"]
platforms = ["linux-64", "osx-64", "win-64"]

[tasks]
lint = "black ."
format = "isort ."
run = { cmd = ["python", "scrambledSeg/training/train.py", "configs/training_config.yaml"], env = { PYTHONPATH = "." } }

[dependencies]
python = "3.10.*"  # Being explicit about Python version
seaborn = ">=0.13.2,<0.14"
kiwisolver = ">=1.4.7,<2"
pytz = ">=2024.2,<2025"
pytest = ">=8.3.4,<9"
scikit-image = ">=0.25.2,<0.26"
psutil = ">=7.0.0,<8"

[pypi-dependencies]
torch = ">=2.0.0"
torchvision = ">=0.15.0"
pytorch-lightning = ">=2.0.0"
albumentations = "==2.0.5"
transformers = ">=4.30.0"
timm = ">=0.9.0"
numpy = ">=1.24.0"
pillow = ">=9.5.0"
h5py = "*"
imagecodecs = "*"
tifffile = "*"
pyyaml = "*"
tqdm = "*"
rich = ">=13.0.0"
pandas = "*"
matplotlib = "*"
scipy = "*"
torchmetrics = "*"
