# Configuration for solid state battery multi-phase segmentation

# Data paths and settings
data_dir: "raw_data"  # Base directory for data
processed_data_dir: "processed_data"  # Directory containing split folders with .tiff files

# Model configuration
model_type: "segformer"  # Type of model to create
encoder_name: "nvidia/segformer-b4-finetuned-ade-512-512"  # mit_b0, mit_b1, mit_b2, mit_b3, mit_b4, mit_b5
pretrained: true
num_classes: 4  # Multi-phase segmentation with 4 classes (0=background, 1-3=different phases)
in_channels: 1  # Single channel input for grayscale images
enable_intermediate_supervision: true  # Enable intermediate supervision in SegFormer (not used)

# Training parameters
num_epochs: 100
batch_size: 8
img_size: [512, 512]
enable_mixed_precision: true  # Using BF16 mixed precision
gradient_accumulation_steps: 2
data_fraction: 0.01  # Fraction of dataset to use

# Dataloader settings
dataloader:
  num_workers: 8
  persistent_workers: true
  pin_memory: true
  cache_size: 500

# Loss function settings for battery segmentation
loss:
  type: "compound"  # Custom compound loss combining Lovász, Focal, and Tversky
  params:
    # Component weights (sum to 1.0)
    lovasz_weight: 0.3    # Optimizes IoU directly
    focal_weight: 0.2     # Focuses on hard examples
    tversky_weight: 0.5   # Balances FP vs FN errors
    
    # Focal Loss parameters
    focal_gamma: 1.5      # Controls focusing strength
    focal_alpha: 0.25     # Class weighting factor
    
    # Tversky Loss parameters (optimized for small structures)
    tversky_alpha: 0.15    # False positive penalty (lower to reduce over-segmentation)
    tversky_beta: 0.85     # False negative penalty (higher to catch small particles)
    
    # Common parameters
    smooth: 1.0           # Smoothing factor
    classes: "present"    # Only consider classes present in batch

# Prediction settings for multi-class segmentation
prediction:
    enable_cleanup: true     # Apply cleanup for each class
    cleanup_kernel_size: 3   # Kernel size for morphological operations
    cleanup_threshold: 5     # Threshold for connected components
    min_hole_size_factor: 32 # Minimum hole size to keep

# Optimizer parameters
optimizer:
  type: AdamW
  params:
    lr: 3.0e-7  # Base learning rate
    weight_decay: 0.01

# Scheduler settings
scheduler:
  type: OneCycleLR
  params:
    max_lr: 0.00025 # 2.5e-4
    epochs: 100
    steps_per_epoch: -1  # Will be set automatically based on dataset size
    pct_start: 0.4
    div_factor: 8
    final_div_factor: 50

# Visualization settings
visualization:
  num_samples: 3  # Number of samples to visualize per epoch
  min_coverage: 0.05  # Minimum percentage of non-background pixels in ground truth
  dpi: 300  # DPI for saved figures
  style: seaborn
  cmap: Set2  # Discrete colormap for multi-class visualization

# Augmentation parameters - optimized for battery material imaging
augmentation:
    # Rotation & flipping - important for orientation-invariant features
    rotate_prob: 0
    rotate_limit: 180
    rotate_border_mode: "constant"
    rotate_border_value: 0
    rotate_mask_border_value: 0
    flip_prob: 0.5
    
    # Intensity augmentation - helps with varying imaging conditions
    brightness_contrast_prob: 0.3
    brightness_limit: 0.2
    contrast_limit: 0.2
    gamma_prob: 0.3
    gamma_limit: [85, 115] 
    
    # Noise augmentation - simulates imaging noise
    gaussian_noise_prob: 0.3
    gaussian_noise_limit: [0.001, 0.04]
    
    # Border handling
    border_mode: "constant"
    border_value: 0
    mask_border_value: 0