# Configuration for synchrotron tomography segmentation with TIFF dataset

# Data paths and settings
data_dir: "raw_data"  # Base directory for data
processed_data_dir: "processed_data"  # Directory containing split folders with .tiff files

# Model configuration
model_type: "segformer"  # Type of model to create
encoder_name: "nvidia/segformer-b2-finetuned-ade-512-512"  # mit_b0, mit_b1, mit_b2, mit_b3, mit_b4, mit_b5
pretrained: true
num_classes: 1  # Binary segmentation
in_channels: 1
enable_intermediate_supervision: true  # Enable intermediate supervision in SegFormer

# Training parameters
num_epochs: 500
batch_size: 8
img_size: [512, 512]
enable_mixed_precision: true
gradient_accumulation_steps: 1
data_fraction: 1.0  # Use full dataset

# Dataloader settings
dataloader:
  num_workers: 8
  persistent_workers: true
  pin_memory: true
  cache_size: 500


# Loss function settings
loss:
  type: "MREAL"  # Use your custom MREAL loss
  params:
    alpha: 0.25        # Weight for positive class in focal component
    gamma: 1.5         # Focus parameter for hard examples
    smooth: 0.0000001   # Smoothing factor for numerical stability
    dice_weight: 0.7   # Base weight for dice vs focal components
    boundary_weight: 0.2  # Weight for boundary enhancement term
    balance_weight: 0.6 # Control the relative weight of the focal and dice components
    enable_logging: true  # Enable detailed loss statistics

thresholding:
    base_threshold: 0.3
    sensitivity: 0.1
    min_hole_size_factor: 64
    enable_adaptive: true
    cleanup_kernel_size: 3
    min_hole_area: 25  # minimum area to preserve holes

# Optimizer parameters
optimizer:
  type: Adam
  params:
    lr: 5.0e-5  # Base learning rate
    weight_decay: 0.001

# Scheduler settings
scheduler:
  type: OneCycleLR
  params:
    max_lr: 0.0005
    epochs: 100
    steps_per_epoch: -1  # Will be set automatically based on dataset size
    pct_start: 0.3
    div_factor: 10
    final_div_factor: 100


# Visualization settings
visualization:
  num_samples: 5  # Number of samples to visualize per epoch
  min_coverage: 0.05  # Minimum percentage of white pixels in ground truth
  dpi: 300  # DPI for saved figures
  style: seaborn
  cmap: viridis

# Augmentation parameters
augmentation:
    rotate_prob: 0.8
    rotate_limit: 180
    rotate_border_mode: "constant"
    rotate_border_value: 0
    rotate_mask_border_value: 0
    flip_prob: 0.5
    brightness_contrast_prob: 0.5
    brightness_limit: 0.1
    contrast_limit: 0.1
    gamma_prob: 0.5
    gamma_limit: [90, 110] 
    gaussian_noise_prob: 0.3
    gaussian_noise_limit: 0.03
    border_mode: "constant"
    border_value: 0
    mask_border_value: 0